### ISSUE TITLE
Report and visualize percentage of users with an avatar set

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-profile-server#139]
We need metrics to determine whether the avatars feature is providing value.  Two key metrics for whether it's being used will be "percent of accounts that have an avatar set" and "percent of accounts active in the last 30 days that have an avatar set".

**Comment by philbooth** [comment]
Was this resolved by https://github.com/mozilla/fxa-profile-server/pull/147?

**Comment by vladikoff** [comment]
> We need metrics to determine whether the avatars feature is providing value.

Using the retention metrics we should be able to answer this:

> "percent of accounts active in the last 30 days that have an avatar set".

Except maybe like this:

`"percent of accounts active in the last 30 days that uploaded an avatar".`
`"percent of accounts active in the last 30 days that fetched an avatar".`

>  "percent of accounts that have an avatar set"

Could `"percent of accounts active in the last 30 days that fetched an avatar".` answer this one?
We can compare how many users fetched an avatar every week and how many didn't? (Using the `avatar.get` event)

> Was this resolved by #147?

Hopefully the "reporting" part of this bug is done, I can start drafting the visualization part even though the data will take some time to arrive.

**Comment by vladikoff** [comment]
depends on the same workflow as https://github.com/mozilla/fxa-auth-db-mysql/issues/84

**Comment by vladikoff** [comment]
Started this dashboard here: https://sql.telemetry.mozilla.org/dashboard/fxa-avatars
