### ISSUE TITLE
/v1/display_name returns 404 if not set

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-profile-server#144]
via irc:
  > jrgm> yeah, so /v1/display_name returns 404 for no name set. What if that was 200 OK with the empty string instead.

**Comment by seanmonstar** [comment]
I like `204 No Content`.

**Comment by rfk** [comment]
The avatar endpoint returns an empty object `{}` if there's no avatar, we could do the same thing here for consistency.

**Comment by shane-tomlinson** [comment]
Asked in triage: will a change from 404 to 204 affect any clients?

**Comment by shane-tomlinson** [comment]
> Asked in triage: will a change from 404 to 204 affect any clients?

@zaach does not believe so.

**Comment by shane-tomlinson** [comment]
@seanmonstar - tag!

**Comment by rfk** [comment]
FWIW you can view the app logs from profile-server at [1].  There seem to be quite a lot of `{status: 403, errno: 999}` responses in amongst the 404s.

[1] https://kibana.fxa.us-west-2.prod.mozaws.net/index.html#/dashboard/elasticsearch/Profile%20App%20Logs

**Comment by rfk** [comment]
> will a change from 404 to 204 affect any clients?

It's not clear to me where these `/v1/display_name` requests are coming from.  None of the logs in the dashboard above include user-agent information.  The content-server has a `getDisplayName` method that would call it, but AFAICT it's not used by any active code.  I can't find references to it in desktop or fennec code.

**Comment by rfk** [comment]
@jrgm is there a profile-server nginx dashboard that we can check against, rather than the app-level logs I linked above?

**Comment by zaach** [comment]
Clients are using the /profile endpoint, which delegates to /display_name IIRC

**Comment by rfk** [comment]
Ah, so profile-server is generating these by talking to itself?

**Comment by seanmonstar** [comment]
Most likely :D

**Comment by jrgm** [comment]
Oauth and Profile nginx are lumped together in 
https://kibana.fxa.us-west-2.prod.mozaws.net/index.html#/dashboard/file/oauth_http_status.json
But here's one with profile-server split out, and only for request:display_name
https://kibana.fxa.us-west-2.prod.mozaws.net/index.html#dashboard/temp/AU_T5Ng73q0_6xopp8hI

However, no 404 there. 

Here they are. But yes, maybe just an internal call. Still, a lot of noise, but since our first-level monitors for http status drive off nginx logs, perhaps not as much an issue for monitoring as I was thinking. Nonetheless, I like 204 better ;-)

**Comment by jrgm** [comment]
> Here they are...

Doh - https://kibana.fxa.us-west-2.prod.mozaws.net/index.html#dashboard/temp/AU_T8ijU3q0_6xopqnK6

**Comment by rfk** [comment]
just bumping this as a gentle reminder that we should target it for the current train
