### ISSUE TITLE
Changing primary email does not invalidate cache

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-profile-server#280]
Need to find a way to signal from the auth server to the profile server redis that the email changed.

**Comment by rfk** [comment]
We might be able to hook up to the new event emitted by https://github.com/mozilla/fxa-auth-server/pull/2066 to drive this

**Comment by grigoryk** [comment]
@vladikoff @rfk does this explain the following behaviour I'm observing?

- Change primary email
- Logout, do stuff...
- Login on a device
- Login with the new primary email
- Payload received from the profile server contains secondary email instead of the new primary email

It probably does. Made for a "fun" afternoon though, until I placed the correct breakpoint :(

**Comment by rfk** [comment]
Sounds like a likely explanation :-(
