### ISSUE TITLE
Provide a default avatar URL if the user hasn't uploaded one?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-profile-server#295]
From discussion in https://github.com/mozilla-lockbox/lockbox-extension/issues/417

We have a nice "placeholder" avatar image that we use in our UI when the user hasn't uploaded a custom image.  For consistency it would be nice for reliers to be able to use the same image.

For users who have not set an avatar image, should we just return the URL of the placeholder image as part of the user's profile data?

**Comment by pdehaan** [comment]
Q: Should it return the URL to the default avatar image, or inline as a data-uri in the response?

**Pro:** One less network request.
**Con:** Inlined response is much larger.

**Comment by IvanDelsinne** [comment]
Returning an URL would require the client to make another request to fetch said avatar, but the client could also choose to not request the image. In the opposite case, in which the client would grab the user's avatar, if not the default, he'd still require it, so I'd say it'd be expected behaviour.

Having links in both situations would keep one concise response type: HTTP(s) URL to an image resource.

Also, if any client would want to not load the icon but provide a locally-stored version, they still could just check the URL against the def. avatar's link (or a list of default avatar's links).

For me, it'd be a yes.

**Comment by vladikoff** [comment]
from mtg: let's do it! Let's make it a URL to the placeholder
