### ISSUE TITLE
Add "locale" field

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-profile-server#85]
This would allow the user to explicitly set their locale.

**Comment by rfk** [comment]
We currently use `locale` in two other places in the FxA ecosystem:

* we record it as part of the core auth data in fxa-auth-server, and use it for sending localized emails
* we publish it to the Basket API when auto-subscribing new users to newsletters, and they record it in their system

It would be great if we could make the profile server the canonical store for this data rather than duplicating it all over the place.  I'm not sure exactly how that might look, but wanted to flag it for consideration as part of this issue.

**Comment by rfk** [comment]
@zaach does this feed into the settings-page work you'll be doing next week, or should we officially put it out-of-scope for Q2?

**Comment by zaach** [comment]
This was not on our agenda for the Settings page so let's call this a stretch/Q3.

**Comment by rfk** [comment]
Plans have changed, we'll now make it possible to read/write this value directly from the fxa-auth-server db as the canonical store
